name: Run Pytest with Selenium

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chrome and ChromeDriver (Optimizado)
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: "stable"  # Usa la versión estable de Chrome
          # No necesitas setup-chromedriver por separado, selenium-manager lo maneja desde 4.6+

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium pytest-html
          # Si usas requirements.txt, asegúrate de incluir pytest-html allí

      - name: Run tests with HTML report
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --junitxml=test-results.xml \
            --html=test-results.html \
            --self-contained-html  # Para un HTML todo-en-uno

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            test-results.xml
            test-results.html